package dev.ysdaeth.autocrypt.encryption;

import dev.ysdaeth.autocrypt.AlgorithmIdentificationException;
import dev.ysdaeth.autocrypt.AlgorithmIdentifier;
import dev.ysdaeth.autocrypt.AlgorithmOutput;

import java.security.Key;
import java.security.KeyException;

/**
 * Encryption manager purpose is to ease data encryption and algorithm detection.
 * Data is encrypted using the algorithm specified with {@link AlgorithmIdentifier} and a secret key.
 * For data decryption, the algorithm is automatically detected based on the metadata  bytes.
 * Encoded bytes array contains:
 * <ol>
 *     <li>Algorithm identifier byte</li>
 *     <li>Algorithm variant byte</li>
 *     <li>Metadata bytes (optional)</li>
 *     <li>Encrypted bytes</li>
 * </ol>
 * Algorithm type byte identifies the algorithm( i.e. 'AES') and variant byte identifies mode (for instance 'GCM')
 * Metadata bytes are optional, and their presence depends on the algorithm implementation.
 * <blockquote><pre>
 *     EncryptionManager manager = new EncryptionManager();
 *     byte[] secret = new byte[]{1,2,3};
 *     SecretKey key = ...;
 *     AlgorithmOutput encoded = manager.encrypt(secret, key, AlgorithmIdentifier.AES_GCM );
 * </pre></blockquote>
 */
public class EncryptionManager {

    /**
     * Returns encoded bytes array, with the algorithm type, algorithm variant, algorithm metadata, and encrypted bytes.
     * <p>Encoded bytes array contains:</p>
     * <ol>
     *     <li>Algorithm identifier byte</li>
     *     <li>Algorithm variant byte</li>
     *     <li>Metadata bytes (optional)</li>
     *     <li>Encrypted bytes</li>
     * </ol>
     * Algorithm type byte identifies the algorithm( i.e. 'AES') and variant byte identifies mode (for instance 'GCM')
     * Metadata bytes are optional, and their presence depends on the algorithm implementation.
     * Encrypted data is always encrypted with the algorithm specified by the {@link AlgorithmIdentifier}
     * If no algorithm was specified, then runtime exception is thrown.
     * <blockquote><pre>
     *     EncryptionManager manager = new EncryptionManager();
     *     byte[] secret = new byte[]{1,2,3};
     *     SecretKey key = ...;
     *     byte[] encrypted = manager.encrypt(secret, key, AlgorithmIdentifier.AES_GCM );
     * </pre></blockquote>
     * @param raw data to be encrypted
     * @param key key for encryption
     * @param identifier algorithm to be used for encryption
     * @return encoded bytes with metadata and encrypted data
     * @throws KeyException when key does not match the algorithm, or is invalid {@link java.security.InvalidKeyException}
     * @throws AlgorithmIdentificationException when {@link AlgorithmIdentifier} was created by using constructor
     * rather than public static fields, and algorithm type or variant can't be found.
     * @throws RuntimeException when failed to encrypt for other reason, i.e: security provider can't
     * provide the instance
     */
    public AlgorithmOutput encrypt(byte[] raw, Key key, AlgorithmIdentifier identifier)
            throws KeyException, AlgorithmIdentificationException {
        Encryptor encryptor = Encryptor.getInstance(identifier);
        return encryptor.encrypt(raw,key);
    }

    /**
     * Resolves algorithm used for encryption and performs decryption operation.
     * Returns decrypted data from the encoded bytes.
     * <blockquote><pre>
     *     EncryptionManager manager = new EncryptionManager();
     *     AlgorithmOutput encoded = //get bytes generated by the algorithm
     *     SecretKey key = ...; // get key for the decryption
     *     byte[] decrypted = manager.decrypt(encoded,key);
     * </pre></blockquote>
     * @param encoded encoded bytes with identifier byte, version byte, metadata bytes and encrypted bytes
     * @param key key to decrypt bytes
     * @return decrypted data
     * @throws KeyException when key does not match the algorithm, not match the secret, or key is invalid.
     * @throws IllegalArgumentException when fails to dynamically select implementation.
     * @throws AlgorithmIdentificationException when algorithm type byte or variant does not
     * match any known implementation
     */
    public byte[] decrypt(AlgorithmOutput encoded, Key key)
            throws AlgorithmIdentificationException, KeyException {
        Encryptor encryptor = Encryptor.getInstance(encoded.getIdentifier());
        return encryptor.decrypt(encoded,key);
    }
}
