package dev.ysdaeth.autocrypt.encryption;

import dev.ysdaeth.autocrypt.AlgorithmIdentificationException;
import dev.ysdaeth.autocrypt.AlgorithmIdentifier;
import dev.ysdaeth.autocrypt.AlgorithmOutput;

import java.security.Key;
import java.security.KeyException;
import java.util.Objects;
import java.util.function.Supplier;

/**
 * Encryption manager purpose is to ease data encryption and algorithm detection.
 * Data is encrypted using the algorithm specified by {@link AlgorithmIdentifier} and a secret key.
 * For data decryption, the algorithm is automatically detected based on the metadata  bytes.
 * Algorithm output are encoded bytes as describe by the {@link AlgorithmOutput}
 * <blockquote><pre>
 *     EncryptionManager manager = new EncryptionManager();
 *     byte[] secret = "secret".getBytes();
 *     SecretKey key = ...;
 *     AlgorithmOutput encoded = manager.encrypt(secret, key, AlgorithmIdentifier.AES_GCM );
 * </pre></blockquote>
 * Class uses {@link EncryptorRegistry#getRegistered(AlgorithmIdentifier)} to provide the encrypting instance.
 * To register custom encryptor use {@link EncryptorRegistry#register(Supplier)}
 */
public class EncryptionManager {
    private final EncryptorRegistry registry;

    public EncryptionManager(EncryptorRegistry registry){
        this.registry = Objects.requireNonNull(registry,"Registry must not be null");
    }

    /**
     * Returns encoded bytes array specified by the {@link AlgorithmOutput}
     * If no algorithm was specified, then runtime exception is thrown.
     * <blockquote><pre>
     *     EncryptionManager manager = new EncryptionManager();
     *     byte[] secret = new byte[]{1,2,3};
     *     SecretKey key = ...;
     *     byte[] encrypted = manager.encrypt(secret, key, AlgorithmIdentifier.AES_GCM );
     * </pre></blockquote>
     * @param raw data to be encrypted
     * @param key key for encryption
     * @param identifier algorithm to be used for encryption
     * @return encoded bytes with metadata and encrypted data
     * @throws KeyException when key does not match the algorithm, or is invalid {@link java.security.InvalidKeyException}
     * @throws AlgorithmIdentificationException when instance assigned to the {@link AlgorithmIdentifier}
     * can't be found.
     * @throws RuntimeException when failed to encrypt for other reason, i.e: security provider can't
     * provide the instance
     */
    public AlgorithmOutput encrypt(byte[] raw, Key key, AlgorithmIdentifier identifier)
            throws KeyException, AlgorithmIdentificationException {
        Encryptor encryptor = registry.getRegistered(identifier);
        return encryptor.encrypt(raw,key);
    }

    /**
     * Resolves algorithm used for encryption and performs decryption operation.
     * Returns decrypted data from the encoded bytes.
     * <blockquote><pre>
     *     EncryptionManager manager = new EncryptionManager();
     *     AlgorithmOutput encoded = //get bytes generated by the algorithm
     *     SecretKey key = ...; // get key for the decryption
     *     byte[] decrypted = manager.decrypt(encoded,key);
     * </pre></blockquote>
     * @param encoded encoded bytes with identifier byte, version byte, metadata bytes and encrypted bytes
     * @param key key to decrypt bytes
     * @return decrypted data
     * @throws KeyException when key does not match the algorithm, not match the secret, or key is invalid.
     * @throws AlgorithmIdentificationException when algorithm type or variant does not
     * match any known implementation
     */
    public byte[] decrypt(AlgorithmOutput encoded, Key key)
            throws AlgorithmIdentificationException, KeyException {
        AlgorithmIdentifier identifier = encoded.getIdentifier();
        Encryptor encryptor = registry.getRegistered(identifier);
        return encryptor.decrypt(encoded,key);
    }
}
